FROM node:18

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del servidor
COPY server/package.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos del servidor
COPY server .

# Exponer el puerto 4000
EXPOSE 4000

# Comando para ejecutar el servidor TCP
CMD ["node", "server.js"]

